# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^.git$"
repos:
  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: "v3.4.2"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.4.2
          - "@prettier/plugin-xml@3.4.1"
          - "prettier-plugin-ini@1.3.0"
        args:
          - --plugin=prettier-plugin-ini
        files: Directory\.Build\.props$|(\.(json|xml|html|config|csproj|xlf|DotSettings|yaml|yml|js|md|xrml|xaml|css|editorconfig)$)
        exclude: NuGetForUnity\.PluginAPI\.xml$
  - repo: local
    hooks:
      - id: resharper-cleanupcode-all
        name: ReSharper Code Cleanup (all files)
        entry: python ./tools/resharper-cleanupcode.py
        language: system
        pass_filenames: false
        require_serial: true
        stages: [manual]
      - id: resharper-cleanupcode-changed
        name: ReSharper Code Cleanup (only changed)
        entry: python ./tools/resharper-cleanupcode.py
        language: system
        files: \.cs$
        pass_filenames: true
        require_serial: true
        stages: [pre-commit, pre-merge-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(pdf|meta|prefab|shader|controller|asset|cginc|mat|unity|anim|shadergraph)$
      - id: end-of-file-fixer
        exclude: \.(asmdef|pdf|meta|prefab|shader|controller|asset|cginc|mat|unity|anim|shadergraph)$
      - id: check-merge-conflict
