name: Create DLL
description: Compiles NuGetForUnity into a .dll that is than used by the final package
inputs:
  version:
    description: The version number
    required: true
runs:
  using: "docker"
  image: "docker://unityci/editor:2018.4.30f1-windows-mono-2"
  args:
    - bash
    - "-c"
    - >-
      wget --no-check-certificate -v --secure-protocol=TLSv1_2 https://dot.net/v1/dotnet-install.sh &&
      source ./dotnet-install.sh --channel STS &&
      rm ./dotnet-install.sh &&
      dotnet build ./src/NuGetForUnity.CreateDll/NuGetForUnity.CreateDll.csproj --nologo -p:AppxBundle=Always -p:Platform='Any CPU' --configuration Release
      -p:ReferencePath=$UNITY_PATH/Editor/Data/Managed -p:Version=${{ inputs.version }} -p:SolutionDir=./ &&
      echo 'Rebuild 'NuGetForUnity.PluginAPI.dll' but without a Version, needed to compare it with the file stored in GIT' &&
      dotnet build --no-incremental --configuration Release ./src/NuGetForUnity.PluginAPI/NuGetForUnity.PluginAPI.csproj -p:DisableCopyJob=true --output ./src/NuGetForUnity/Editor/PluginAPI
