namespace NugetForUnity
{
    /// <summary>
    ///     The configuration for a single NuGet package, stored in the <c>package.conf</c> (<see cref="PackagesConfigFile" />).
    /// </summary>
    public class PackageConfig : NugetPackageIdentifier
    {
        /// <summary>
        ///     Gets or sets a value indicating whether the assemblies (*.dll files) of this NuGet package should be automatically referenced.
        ///     Assemblies with this setting are automatically referenced by the sup projects generated by Unity.
        ///     When this setting is set to <c>false</c> the assemblies of this NuGet package are only referenced
        ///     by Unity projects that explicitly list them inside there <c>*.asmdef</c> file.
        /// </summary>
        public bool AutoReferenced { get; set; } = true;
    }
}
